version: '3.1'

services:
    postgres_database:
        container_name: postgres_database
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dev_database
        ports:
            - "5435:5432"
        volumes:
            - ./database-postgres:/docker-entrypoint-initdb.d